"""new

Revision ID: f3f6b1a86d5e
Revises: 84c11722ce15
Create Date: 2025-07-31 00:49:52.976236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f6b1a86d5e'
down_revision: Union[str, Sequence[str], None] = '84c11722ce15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_likes',
    sa.Column('like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo_owner_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('liked_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.add_column('search_params', sa.Column('age_weight', sa.Float(), nullable=True))
    op.add_column('search_params', sa.Column('interests_weight', sa.Float(), nullable=True))
    op.add_column('search_params', sa.Column('groups_weight', sa.Float(), nullable=True))
    op.add_column('search_params', sa.Column('friends_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('search_params', 'friends_weight')
    op.drop_column('search_params', 'groups_weight')
    op.drop_column('search_params', 'interests_weight')
    op.drop_column('search_params', 'age_weight')
    op.drop_table('photo_likes')
    # ### end Alembic commands ###
